# -*- coding: utf-8 -*-
"""EDA Traindata.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XepaDwE3NOQZTqCnB_Q-kvJmygpRlQeu
"""

import pandas as pd
import numpy as np

traindata = pd.read_csv("train.csv")

traindata.shape

traindata.info()

traindata.duplicated().sum()

traindata["views"] = pd.to_numeric(train.views, errors='coerce')
traindata.info()

traindata.drop(['Unnamed: 17'],axis=1,inplace=True)
traindata.drop(['Unnamed: 18'],axis=1,inplace=True)

traindata.describe()

traindata['category_id'].value_counts()

traindata['category_id'].value_counts().plot(kind='bar')

import matplotlib.pyplot as plt

plt.scatter(traindata['subscriber'], traindata['views'],marker="*", color="red")

traindata['subscriber'].plot(kind='box')

traindata['views'].plot(kind='box')

traindata.mean()

traindata.median()

